#![allow(dead_code)]

use reqwest::header::{AUTHORIZATION, CONTENT_TYPE};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::error::Error;

#[derive(Clone, Debug, Serialize, Deserialize)]
/// AI Response - Message content from LLM
pub struct ChatCompletionMessage {
    /// The contents of the message.
    #[serde(default)]
    pub content: Option<String>,

    /// The refusal message generated by the model.
    #[serde(default)]
    pub refusal: Option<String>,

    /// The role of the author of this message.
    pub role: String,

    /// Whether the Model wants to use a tool and if so, which tool.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,
    // TODO
    // - annotations
}
#[derive(Clone, Debug, Serialize, Deserialize)]
/// AI Response - Tool call requested by LLM
pub struct ToolCall {
    pub id: String,
    // The type of the tool. Currently, only function is supported.
    #[serde(rename = "type")]
    pub tool_type: String,
    pub function: ResponseFunction,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
/// AI Response - Function that LLM wants to call
pub struct ResponseFunction {
    pub name: String,
    pub arguments: serde_json::Value,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
/// AI Request - Tool definition sent to LLM
pub struct Tool {
    /// The Function name
    pub function: Function,

    #[serde(rename = "type")]
    pub tool_type: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
/// AI Request - Available functions for tools
pub struct Function {
    pub name: String,
    pub description: String,
    /// Flexible for json values
    pub parameters: serde_json::Value,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
/// AI Response - One possible answer choice from LLM
pub struct Choice {
    /// The reason the model stopped generating tokens. This will be `stop` if the model hit
    /// a natural stop point or a provided stop sequence, `length` if the maximum number of
    /// tokens specified in the request was reached, `content_filter` if content was omitted due
    /// to a flag from our content filters, `tool_calls` if the model called a tool, or
    /// `function_call` (deprecated) if the model called a function.
    pub finish_reason: String,

    /// The index of the choice in the list of choices.
    pub index: i32,

    /// A chat completion message generated by the model.
    pub message: ChatCompletionMessage,
    // TODO
    // - logprobs
}

#[derive(Debug, Serialize, Deserialize)]
/// AI Response
pub struct TokenDetail {
    /// When using Predicted Outputs, the number of tokens in the prediction that appeared in the completion.
    pub accepted_prediction_tokens: i32,

    /// Tokens generated by the model for reasoning.
    pub reasoning_tokens: i32,

    /// When using Predicted Outputs, the number of tokens in the prediction that did not appear
    /// in the completion. However, like reasoning tokens, these tokens are still counted in the
    /// total completion tokens for purposes of billing, output, and context window limits.
    pub rejected_prediction_tokens: i32,
}

#[derive(Debug, Serialize, Deserialize)]
/// AI Response - Usage statistics for billing/monitoring  
pub struct UsageStatistic {
    /// Number of tokens in the generated completion.
    pub completion_tokens: i32,

    /// Number of tokens in the prompt.
    pub prompt_tokens: i32,

    /// Total number of tokens used in the request (prompt + completion).
    pub total_tokens: i32,

    /// Breakdown of tokens used in a completion.
    #[serde(default)]
    pub completion_tokens_details: Option<TokenDetail>,
    // TODO
    // - prompt_tokens_details
}
/// AI Request
#[derive(Debug, Serialize, Deserialize, Clone)]
pub enum ToolChoice {
    /// Dynamic tool calls - the model chooses wheter to use tools
    /// and which tool is used
    #[serde(rename = "auto")]
    Auto,
    /// Disallow tools calls
    #[serde(rename = "none")]
    None,
    // #[serde(rename="required")]
    // Required,
}

#[derive(Debug, Serialize, Deserialize)]
/// AI Response
pub struct Completion {
    /// A list of chat completion choices. Can be more than one if `n` is greater than 1.
    pub choices: Vec<Choice>,

    /// A unique identifier for the chat completion.
    #[serde(default)]
    pub id: Option<String>,

    /// The object type, which is always `chat.completion`.
    #[serde(default)]
    pub object: Option<String>,

    /// The Unix timestamp (in seconds) of when the chat completion was created
    #[serde(default)]
    pub created: Option<u64>,

    /// The model used for the chat completion.
    #[serde(default)]
    pub model: Option<String>,

    /// Usage statistics for the completion request.
    pub usage: UsageStatistic,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
/// AI Request
pub struct Message {
    /// The contents of the message
    pub content: String,

    /// The role of the messages author, can be one of:
    /// - developer
    /// - system
    /// - user
    /// - assistant
    /// - tool
    ///
    /// The exact purposes of the roles can be found at
    /// https://platform.openai.com/docs/api-reference/chat/create#chat-create-messages
    pub role: String,

    /// An optional name for the participant, to be used for differentiating between participants of the same role
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
/// AI Request
pub struct CompletionBody {
    /// A list of messages comprising the conversation so far
    pub messages: Vec<Message>,

    /// Model ID used to generate the response
    pub model: String,

    /// Optional List of Tools
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<Tool>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_choice: Option<ToolChoice>,

    /// Sampling temperature to use (higher values mean more randomness).
    /// Range: 0.0 to 2.0.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f32>,

    /// Nucleus sampling parameter. An alternative to temperature sampling.
    /// The model considers results of the tokens with top_p probability mass.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub top_p: Option<f32>,

    /// Whether to stream back partial progress (token by token).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stream: Option<bool>,

    /// Number between -2.0 and 2.0. Positive values penalize new tokens based on
    /// their existing frequency in the text so far, decreasing the model's likelihood
    /// to repeat the same line verbatim.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub frequency_penalty: Option<f32>,

    /// Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub presence_penalty: Option<f32>,

    /// How many chat completion choices to generate for each input message. Default is `1`
    #[serde(skip_serializing_if = "Option::is_none")]
    pub n: Option<i32>,

    /// Modify the likelihood of specified tokens appearing in the completion.
    //
    // Accepts a JSON object that maps tokens (specified by their token ID in the tokenizer)
    /// to an associated bias value from -100 to 100. Mathematically, the bias is added to
    /// the logits generated by the model prior to sampling. The exact effect will vary per
    /// model, but values between -1 and 1 should decrease or increase likelihood of selection;
    /// values like -100 or 100 should result in a ban or exclusive selection of the relevant token.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logit_bias: Option<HashMap<String, i32>>,

    /// Whether to return log probabilities of the output tokens or not. If true, returns the log
    /// probabilities of each output token returned in the `content` of `message`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logprobs: Option<bool>,

    /// An upper bound for the number of tokens that can be generated for a completion,
    /// including visible output tokens and reasoning tokens.
    /// Not all APIs support this feature, `max_tokens` is more stable
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_completion_tokens: Option<i32>,

    /// The maximum number of tokens that can be generated in the chat completion.
    /// This value can be used to control costs for text generated via API.
    //
    // This value is marked as deprecated in the openai API docs in favor of max_completion_tokens
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<i32>,

    /// A unique identifier representing your end-user, to help OpenAI monitor and detect abuse.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
}

pub fn fetch_completion(
    base_url: &reqwest::Url,
    api_key: &str,
    body: &CompletionBody,
    client: reqwest::blocking::Client,
) -> Result<Completion, Box<dyn Error>> {
    let authorization = format!("Bearer {api_key}");
    let json_body = serde_json::to_string(body)?;

    let mut url = base_url.clone();
    url.set_path(&(url.path().to_owned() + "/chat/completions"));

    let response = client
        .post(url)
        .header(AUTHORIZATION, authorization)
        .header(CONTENT_TYPE, "application/json")
        .body(json_body)
        .send()?;

    if response.status().is_success() {
        let openai_response: Completion = response.json()?;
        Ok(openai_response)
    } else {
        let error = response.text()?;
        Err(format!("API Error: {error}").into())
    }
}
