name: Container Build
run-name: ${{ github.event.workflow_run.head_commit.message }}

on:
  workflow_run:
    workflows: ["Rust CI"]
    branches: ["feature/build_container_image"]
    types:
      - completed

  #push:
    #branches:
      #- feature/build_container_image


permissions:
  contents: read
  packages: write
  statuses: write

jobs:
  build-minion-x86-64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Container Image (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Containerfile
          push: false             # Nur zum Createn, nicht pushen
          tags: ghcr.io/autominion/teamprojekt-agents:x86-64-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
